from manimlib.imports import *
class Solution(Scene):
	def construct(self):
		Solve = TexMobject(r" Solve \ for \ x:")
		Solve.to_edge(UP)
		self.play(Write(Solve))
		self.wait(2)
		R0 = TexMobject(r" x^2 + 2 x + 3 = 0")
		self.play(Write(R0))
		self.wait(2)
		R1 = TexMobject(r" Subtract \ 3 \ from \ both \ sides:")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" x^2 + 2 x = -3")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" Add \ 1 \ to \ both \ sides:")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" x^2 + 2 x + 1 = -2")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" Write \ the \ left \ hand \ side \ as \ a \ square:")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" (x + 1)^2 = -2")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" Take \ the \ square \ root \ of \ both \ sides:")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" x + 1 = \sqrt{2} \ or -\sqrt{2}")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" Subtract \ 1 \ from \ both \ sides:")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" x = \sqrt{2} - \sqrt{2} or \ x + \sqrt{2} = -\sqrt{2}")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" Subtract \ 1 \ from \ both \ sides:")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" Answer \ : x = \pm i \sqrt{2} - 1 \ or \ -\i \sqrt{2} - 1")
		self.play(Transform(R0,R1))
		self.wait(2)
		R1 = TexMobject(r" ")
		self.play(Transform(R0,R1))
		self.wait(2)
		self.play(FadeOut(R0))