from manimlib.imports import *
from math import *
class Solution(GraphScene):
	def construct(self):
		watermark = ImageMobject("./assets/water_mark.png")
		watermark.scale(1.5)
		watermark.to_corner(DOWN+RIGHT, buff=0)
		self.play(FadeIn(watermark))
		Solve = TexMobject(r" Solve \ for \ x \ over \ the \ real \ numbers:")
		Solve.to_edge(UP)
		self.play(Write(Solve))
		self.wait(2)
		R0 = TexMobject(r" x^{2} - 4 = 0")
		R1 = TexMobject(r" The \ left \ hand \ side \ factors \ into \ a \ product \ with \ two \ terms:")
		R2 = TexMobject(r" (x - 2) (x + 2) = 0")
		R3 = TexMobject(r" Split \ into \ two \ equations:")
		R4 = TexMobject(r" x - 2 = 0 \ or \ x + 2 = 0")
		R5 = TexMobject(r" Add 2 \ to \ both \ sides:")
		R6 = TexMobject(r" x = 2 \ or \ x + 2 = 0")
		R7 = TexMobject(r" Subtract \ 2 \ from \ both \ sides:")
		R8 = TexMobject(r" Answer: x = 2 \ or \ x = -2")
		R0.shift([0,0.7,0])
		self.play(Write(R0))
		self.wait(1)
		R1.next_to(R0, DOWN)
		self.play(Write(R1))
		self.wait(1)
		R2.next_to(R1, DOWN)
		self.play(Write(R2))
		self.wait(1)
		self.play(FadeOut(R0))
		self.play(ApplyMethod(R1.shift,[0,0.7,0]))
		self.play(ApplyMethod(R2.next_to,R1, DOWN))
		R3.next_to(R2, DOWN)
		self.play(Write(R3))
		self.play(FadeOut(R1))
		self.play(ApplyMethod(R2.shift,[0,0.7,0]))
		self.play(ApplyMethod(R3.next_to,R2, DOWN))
		R4.next_to(R3, DOWN)
		self.play(Write(R4))
		self.play(FadeOut(R2))
		self.play(ApplyMethod(R3.shift,[0,0.7,0]))
		self.play(ApplyMethod(R4.next_to,R3, DOWN))
		R5.next_to(R4, DOWN)
		self.play(Write(R5))
		self.play(FadeOut(R3))
		self.play(ApplyMethod(R4.shift,[0,0.7,0]))
		self.play(ApplyMethod(R5.next_to,R4, DOWN))
		R6.next_to(R5, DOWN)
		self.play(Write(R6))
		self.play(FadeOut(R4))
		self.play(ApplyMethod(R5.shift,[0,0.7,0]))
		self.play(ApplyMethod(R6.next_to,R5, DOWN))
		R7.next_to(R6, DOWN)
		self.play(Write(R7))
		self.play(FadeOut(R5))
		self.play(ApplyMethod(R6.shift,[0,0.7,0]))
		self.play(ApplyMethod(R7.next_to,R6, DOWN))
		R8.next_to(R7, DOWN)
		self.play(Write(R8))
		self.play(FadeOut(R8))
		self.play(FadeOut(R7))
		self.play(FadeOut(R6))
		self.play(FadeOut(Solve))
		