from manimlib.imports import *
from math import *
class Solution(GraphScene):
	def construct(self):
		watermark = ImageMobject("./assets/water_mark.png")
		watermark.scale(1.5)
		watermark.to_corner(DOWN+RIGHT, buff=0)
		self.play(FadeIn(watermark))
		Solve = TexMobject(r" Compute \ the \ definite \ integral:")
		Solve.to_edge(UP)
		self.play(Write(Solve))
		self.wait(2)
		R0 = TexMobject(r" \int_{-4}^{4} \sqrt{16 - x^{2}} dx")
		R1 = TexMobject(r" For \ the \ integrand \ sqrt{16 - x^{2}}, \ substitute \ x = 4 \sin(u) \ and \ dx = 4 \cos(u) \ du.")
		R2 = TexMobject(r" Then \sqrt{16 - x^{2}} = \sqrt{16 - 16 \sin^2(u)} = 4 \sqrt{ \cos^2(u)}.")
		R3 = TexMobject(r" This \ substitution \ is \ invertible \ over \ - \frac{π}{2}<u<\frac{π}{2} \ with \ inverse \ u = \sin^{-1}(x/4).")
		R4 = TexMobject(r" This \ gives \ a \ new \ lower \ bound \ u = \sin^{-1}(-4/4) = -\frac{\pi}{2} \ and \ upper \ bound \ u = \sin^{-1}(4/4) = \frac{\pi}{2}:")
		R5 = TexMobject(r" = 4 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} 4 \cos(u) \sqrt{\cos^2(u)} du")
		R6 = TexMobject(r" Factor \ out \ constants:")
		R7 = TexMobject(r" = 16 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} \cos(u) \sqrt{\cos^2(u)} du")
		R8 = TexMobject(r" Simplify \ cos(u) \sqrt{ \cos^{2}(u)} \ assuming \ -\frac{\pi}{2}<u<\frac{\pi}{2}")
		R9 = TexMobject(r" = 16 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} \cos^2(u) du")
		R10 = TexMobject(r" Write \cos^{2}(u) \ as \ 1/2 \cos(2 u) + 1/2:")
		R11 = TexMobject(r" = 16 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} (\frac{1}{2} \cos(2 u) + \frac{1}{2}) du")
		R12 = TexMobject(r" Integrate \ the \ sum \ term \ by \ term \ and \ factor \ out \ constants:")
		R13 = TexMobject(r" = 8 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} \cos(2 u) du + 8 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} 1 du")
		R14 = TexMobject(r" For \ the \ integrand \ cos(2 u), \ substitute \ s = 2 u \ and \ ds = 2 du.")
		R15 = TexMobject(r" This \ gives \ a \ new \ lower \ bound \ s = (-\pi) / 2 = -\pi \ and \ upper \ bound \ s = (\pi) / 2 = \pi:")
		R16 = TexMobject(r" = 4 \int_{-\pi}^{\pi} \cos(s) ds + 8 \int_{-\pi/2}^{\pi/2} 1 du")
		R17 = TexMobject(r" Apply \ the \ fundamental \ theorem \ of \ calculus.")
		R18 = TexMobject(r" The \ antiderivative \ of \ cos(s) \ is \ sin(s):")
		R19 = TexMobject(r" = 4 \sin(s) \right \bracketing \bar _{(-\pi)^\pi + 8} \int_{-\pi/2}^{\pi/2} 1 du")
		R20 = TexMobject(r" Evaluate \ the \ antiderivative \ at \ the \ limits \ and \ subtract.")
		R21 = TexMobject(r" 4 \sin(s) \right \bracketing \ bar \ (-\pi)^\pi = 4 \sin(\pi) - 4 \sin(-\pi) = 0:")
		R22 = TexMobject(r" = 8 \int_{-\frac{\pi}{2}}^{\frac{\pi}{2}} 1 du")
		R23 = TexMobject(r" Apply \ the \ fundamental \ theorem \ of \ calculus.")
		R24 = TexMobject(r" The \ antiderivative \ of \ 1 \ is \ u:")
		R25 = TexMobject(r" = 8 u _{-\frac{\pi}{2}}^{\frac{\pi}{2}}")
		R26 = TexMobject(r" Evaluate \ the \ antiderivative \ at \ the \ limits \ and \ subtract.")
		R27 = TexMobject(r" 8 u \ right \ bracketing \ bar \ (-\pi/2)^{(\pi/2)} = (8 \pi)/2 - ((8 (-\pi))/2) = 8 \pi:")
		R28 = TexMobject(r" Answer: = 8\pi")
		R0.shift([0,0.7,0])
		self.play(Write(R0))
		self.wait(1)
		R1.next_to(R0, DOWN)
		self.play(Write(R1))
		self.wait(1)
		R2.next_to(R1, DOWN)
		self.play(Write(R2))
		self.wait(1)
		self.play(FadeOut(R0))
		self.play(ApplyMethod(R1.shift,[0,0.7,0]))
		self.play(ApplyMethod(R2.next_to,R1, DOWN))
		R3.next_to(R2, DOWN)
		self.play(Write(R3))
		self.play(FadeOut(R1))
		self.play(ApplyMethod(R2.shift,[0,0.7,0]))
		self.play(ApplyMethod(R3.next_to,R2, DOWN))
		R4.next_to(R3, DOWN)
		self.play(Write(R4))
		self.play(FadeOut(R2))
		self.play(ApplyMethod(R3.shift,[0,0.7,0]))
		self.play(ApplyMethod(R4.next_to,R3, DOWN))
		R5.next_to(R4, DOWN)
		self.play(Write(R5))
		self.play(FadeOut(R3))
		self.play(ApplyMethod(R4.shift,[0,0.7,0]))
		self.play(ApplyMethod(R5.next_to,R4, DOWN))
		R6.next_to(R5, DOWN)
		self.play(Write(R6))
		self.play(FadeOut(R4))
		self.play(ApplyMethod(R5.shift,[0,0.7,0]))
		self.play(ApplyMethod(R6.next_to,R5, DOWN))
		R7.next_to(R6, DOWN)
		self.play(Write(R7))
		self.play(FadeOut(R5))
		self.play(ApplyMethod(R6.shift,[0,0.7,0]))
		self.play(ApplyMethod(R7.next_to,R6, DOWN))
		R8.next_to(R7, DOWN)
		self.play(Write(R8))
		self.play(FadeOut(R6))
		self.play(ApplyMethod(R7.shift,[0,0.7,0]))
		self.play(ApplyMethod(R8.next_to,R7, DOWN))
		R9.next_to(R8, DOWN)
		self.play(Write(R9))
		self.play(FadeOut(R7))
		self.play(ApplyMethod(R8.shift,[0,0.7,0]))
		self.play(ApplyMethod(R9.next_to,R8, DOWN))
		R10.next_to(R9, DOWN)
		self.play(Write(R10))
		self.play(FadeOut(R8))
		self.play(ApplyMethod(R9.shift,[0,0.7,0]))
		self.play(ApplyMethod(R10.next_to,R9, DOWN))
		R11.next_to(R10, DOWN)
		self.play(Write(R11))
		self.play(FadeOut(R9))
		self.play(ApplyMethod(R10.shift,[0,0.7,0]))
		self.play(ApplyMethod(R11.next_to,R10, DOWN))
		R12.next_to(R11, DOWN)
		self.play(Write(R12))
		self.play(FadeOut(R10))
		self.play(ApplyMethod(R11.shift,[0,0.7,0]))
		self.play(ApplyMethod(R12.next_to,R11, DOWN))
		R13.next_to(R12, DOWN)
		self.play(Write(R13))
		self.play(FadeOut(R11))
		self.play(ApplyMethod(R12.shift,[0,0.7,0]))
		self.play(ApplyMethod(R13.next_to,R12, DOWN))
		R14.next_to(R13, DOWN)
		self.play(Write(R14))
		self.play(FadeOut(R12))
		self.play(ApplyMethod(R13.shift,[0,0.7,0]))
		self.play(ApplyMethod(R14.next_to,R13, DOWN))
		R15.next_to(R14, DOWN)
		self.play(Write(R15))
		self.play(FadeOut(R13))
		self.play(ApplyMethod(R14.shift,[0,0.7,0]))
		self.play(ApplyMethod(R15.next_to,R14, DOWN))
		R16.next_to(R15, DOWN)
		self.play(Write(R16))
		self.play(FadeOut(R14))
		self.play(ApplyMethod(R15.shift,[0,0.7,0]))
		self.play(ApplyMethod(R16.next_to,R15, DOWN))
		R17.next_to(R16, DOWN)
		self.play(Write(R17))
		self.play(FadeOut(R15))
		self.play(ApplyMethod(R16.shift,[0,0.7,0]))
		self.play(ApplyMethod(R17.next_to,R16, DOWN))
		R18.next_to(R17, DOWN)
		self.play(Write(R18))
		self.play(FadeOut(R16))
		self.play(ApplyMethod(R17.shift,[0,0.7,0]))
		self.play(ApplyMethod(R18.next_to,R17, DOWN))
		R19.next_to(R18, DOWN)
		self.play(Write(R19))
		self.play(FadeOut(R17))
		self.play(ApplyMethod(R18.shift,[0,0.7,0]))
		self.play(ApplyMethod(R19.next_to,R18, DOWN))
		R20.next_to(R19, DOWN)
		self.play(Write(R20))
		self.play(FadeOut(R18))
		self.play(ApplyMethod(R19.shift,[0,0.7,0]))
		self.play(ApplyMethod(R20.next_to,R19, DOWN))
		R21.next_to(R20, DOWN)
		self.play(Write(R21))
		self.play(FadeOut(R19))
		self.play(ApplyMethod(R20.shift,[0,0.7,0]))
		self.play(ApplyMethod(R21.next_to,R20, DOWN))
		R22.next_to(R21, DOWN)
		self.play(Write(R22))
		self.play(FadeOut(R20))
		self.play(ApplyMethod(R21.shift,[0,0.7,0]))
		self.play(ApplyMethod(R22.next_to,R21, DOWN))
		R23.next_to(R22, DOWN)
		self.play(Write(R23))
		self.play(FadeOut(R21))
		self.play(ApplyMethod(R22.shift,[0,0.7,0]))
		self.play(ApplyMethod(R23.next_to,R22, DOWN))
		R24.next_to(R23, DOWN)
		self.play(Write(R24))
		self.play(FadeOut(R22))
		self.play(ApplyMethod(R23.shift,[0,0.7,0]))
		self.play(ApplyMethod(R24.next_to,R23, DOWN))
		R25.next_to(R24, DOWN)
		self.play(Write(R25))
		self.play(FadeOut(R23))
		self.play(ApplyMethod(R24.shift,[0,0.7,0]))
		self.play(ApplyMethod(R25.next_to,R24, DOWN))
		R26.next_to(R25, DOWN)
		self.play(Write(R26))
		self.play(FadeOut(R24))
		self.play(ApplyMethod(R25.shift,[0,0.7,0]))
		self.play(ApplyMethod(R26.next_to,R25, DOWN))
		R27.next_to(R26, DOWN)
		self.play(Write(R27))
		self.play(FadeOut(R25))
		self.play(ApplyMethod(R26.shift,[0,0.7,0]))
		self.play(ApplyMethod(R27.next_to,R26, DOWN))
		R28.next_to(R27, DOWN)
		self.play(Write(R28))
		self.play(FadeOut(R28))
		self.play(FadeOut(R27))
		self.play(FadeOut(R26))
		self.play(FadeOut(Solve))
		