from manimlib.imports import *
class Solution(Scene):
    def construct(self):
        Solve = TexMobject(r"Solve \ x + 2 = 10")
        R0 = TexMobject(r"x = 8")
        R1 = TexMobject(r"Solve \ for \ x:")
        R2 = TexMobject(r"x + 2 = 10")
        R3 = TexMobject(r"Subtract \ 2 \ from \ both \ sides:")
        R4 = TexMobject(r"x + (2 - 2) = 10 - 2")
        R5 = TexMobject(r"2 - 2 = 0:")
        R6 = TexMobject(r"x = 10 - 2")
        R7 = TexMobject(r"10 - 2 = 8:")
        R8 = TexMobject(r"Answer \ : x = 8")

        Solve.to_edge(UP)
        self.play(Write(Solve))
        self.wait(2)
        self.play(Write(R1))
        self.wait(2)
        self.play(Transform(R1,R2))
        self.wait(2)
        self.play(Transform(R1,R3))
        self.wait(2)
        self.play(Transform(R1,R4))
        self.wait(2)
        self.play(Transform(R1,R5))
        self.wait(2)
        self.play(Transform(R1,R6))
        self.wait(2)
        self.play(Transform(R1,R7))
        self.wait(2)
        self.play(Transform(R1,R8))
        self.wait(2)
        self.play(FadeOut(R1))
